<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SaxonEngine.fs" />
    <Compile Include="Tools.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
    <PackageReference Include="SaxonCS-HE" Version="13.0.0" />
  </ItemGroup>

</Project>
